[package]
name = "watermark-filter"
version = "0.1.0"
authors = ["六翁 <lu.hl@alibaba-inc.com>"]
edition = "2018"

[lib]
name = "watermark_filter"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.1.3"
log = "0.4.13"